language: python

matrix:
  include:
  # Ubuntu 14.04.3 LTS
    - os: linux
      dist: trusty
      python: '2.7'
      env: PAGER=/bin/cat
    - os: linux
      dist: trusty
      python: '3.3'
      env: PAGER=/bin/cat
    - os: linux
      dist: trusty
      python: '3.4'
      env: PAGER=/bin/cat
    - os: linux
      dist: trusty
      python: '3.5'
      env: PAGER=/bin/cat

#matrix:
#  include:
#    - os: linux
#      python: '2.6'
#      env: PAGER=/bin/cat

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq pigz

install:
    - ./bootstrap.sh

script:
    - cd travis_example/
    - ./../uap travis_uap_config.yaml status
