# This is the rnaseq-pipeline configuration file. Important: save this file as config.yaml!
sourcePaths:
    - [in path]
destinationPath: [out path]
steps: |
    - cutadapt {
        adapter-R1: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC((INDEX))ATCTCGTATGCCGTCTTCTGCTTG"
        adapter-R2: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT"
        }
        - fix_cutadapt
tools:
    pigz:
        path: 'pigz'
        get_version: '--version'
