# This is the rnaseq-pipeline configuration file. Important: save this file as config.yaml!

# paths to flow cell directories
sourcePaths:
  - /gpfs1/data/bioinf/Data/120809_SN928_0081_AD11Y3ACXX_Keep
  - [more paths...]
# this is where output files go
destinationPath: [path]
steps: |
  - cutadapt
    - remove_empty_fastq_sequences
      - segemehl
    - analyze_cutadapt
